# -*- coding: utf-8 -*-
"""Data-Driven Insights.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1nZGSHKSPTz18Osiv6-AfRuiA28q4EPTz

📘 Instrução – Mini Projeto: Data-Driven Insights (Módulo 01)
🧑‍💻 Projeto
Você deverá criar um projeto prático de exploração e visualização de dados com Python no Google Colab, utilizando uma das bases indicadas abaixo ou outra de sua escolha, desde que esteja no formato .csv.

🎯 Objetivo
Explorar, transformar e visualizar dados com base em estruturas do Python e bibliotecas como pandas, numpy e matplotlib, gerando insights descritivos a partir da análise.

✅ Entregáveis
Notebook Colab com o nome: data_driven_insights.ipynb

O notebook deve conter:

Uso de listas, dicionários e tuplas com os dados

Estruturas condicionais (if/elif/else) e loops (for, while)

Manipulação de colunas com pandas

Operações com arrays NumPy

Filtragens, agrupamentos e resumos com pandas

Gráficos (linha, barras e dispersão) com matplotlib

Comentários e insights ao longo do notebook usando Markdown

Um relatório final em Markdown com os principais aprendizados e descobertas

Publicação no GitHub:

Criar um repositório com o nome: data-driven-insights

Subir o notebook final no repositório

📊 Bases de dados sugeridas
Você pode escolher uma das opções abaixo ou outra de sua preferência:

🎓 Dados de desempenho escolar: https://archive.ics.uci.edu/dataset/320/student+performance

🛍️ Dados de vendas simuladas: https://www.kaggle.com/datasets/kyanyoga/sample-sales-data

Dica: certifique-se de entender bem as colunas da base escolhida antes de começar a análise.

🦮 Conteúdo Guiado
Abaixo você tem o conteúdo guiado para ajudar no desenvolvimento do projeto.

Siga o passo-a-passo e suba seu projeto para o repositório do Github.

1. Importação de Bibliotecas
Importe pandas, numpy e matplotlib.pyplot.
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

"""2. Leitura e Exploração Inicial da Base
Carregue o arquivo CSV escolhido usando pandas.
Mostre as 5 primeiras linhas.
Mostre o nome das colunas, a quantidade de linhas/colunas e tipos de dados detectados pelo pandas (.dtypes).
Explique em Markdown os principais tipos de dados encontrados (str, int, float, ...).
"""

#carregando um arquivo temporário para o notebook
from google.colab import files

# Abre o diálogo para upload
uploaded = files.upload()

df = pd.read_csv("sales_data_sample.csv")  # Lendo o arquivo CSV

"""Mostrando os nomes das colunas, a quantidade de linhas/colunas e tipos de dados detectados pelo pandas (.dtypes)"""

print("Head")
print(df.head())
print("Shape")
print(df.shape)
print("Columns")
print(df.columns)
print("Dtypes")
print(df.dtypes)

"""Insights, verificado que a base possui 25 colunas e 2823 linhas, os tipos dos dados como: float, int e object, possui colunas com "NaN"

3. Listas, Dicionários e Tuplas
Extraia uma coluna de interesse em uma lista Python e faça um loop imprimindo informações sobre cada item.
Monte um dicionário relacionando dois campos importantes da base (ex: produto:categoria, filme:gênero, aluno:disciplina) e exiba 3 pares.
Crie uma tupla contendo três informações distintas de uma linha e imprima o resultado.
"""

print(df.head())

"""Usando a coluna CITY como exemplo"""

# Lista: Listando a coluna CITY
nomes = list(df['CITY'])
for nome in nomes[:5]:
    print(nome)

print(df['STATUS'],df['PRODUCTLINE'])

# Lista: Listando a coluna STATUS, para verifica quais são os status
nomes = list(df['STATUS'].unique())
for nome in nomes[:50]:
    print(nome)

"""Usando dicionario com o exemplo das colunas COUNTRY e STATE"""

# Dicionário: chave e valor, exemplo (nome:categoria)
dicionario = dict(zip(df['COUNTRY'][:3], df['STATE'][:3]))
print(dicionario)
# Se não tiver outra coluna str, pode repetir 'Escolha_Coluna_STR'

"""Usando Tupla como exemplo das colunas PRODUCTLINE, STATUS e SALES"""

# Tupla: informações de uma linha
linha0 = df.iloc[0]
minha_tupla = (linha0['PRODUCTLINE'], linha0['STATUS'], linha0['SALES'])
print(minha_tupla)

"""Insight: analisando a coluna PRODUCTLINE, foi verificado que é uma base de venda de varios tipos de veiculos como: Avião, Navio, Carros etc.., com os status: Shipped, Disputed, In Process, Cancelled, On Hold, Resolved

4. Estruturas Condicionais e Laços
Escolha uma coluna numérica de interesse na base (exemplo: nota, preço, quantidade, etc) e utilize uma estrutura condicional (if/elif/else) para imprimir uma mensagem de acordo com o valor de um elemento (por exemplo, se é alto, médio ou baixo).
Use um laço for para calcular a soma (ou outra operação, como média ou multiplicação) dos primeiros 5 valores dessa coluna e mostre o resultado.
Empregue um laço while para encontrar (ou contar) o primeiro valor da mesma coluna que atenda a uma determinada condição (por exemplo: maior que um certo número, diferente de zero, etc) e exiba esse valor quando encontrado.
"""

print(df.head())

# Escolha uma coluna numérica adequada
coluna_numerica = 'PRICEEACH'
primeiro_valor = df[coluna_numerica][0]

#Verificando os valores da coluna
print(df[coluna_numerica].describe())

if primeiro_valor > 80.000000:
    print("Valor alto")
elif primeiro_valor > 50.000000:
    print("Valor intermediário")
else:
    print("Valor baixo")

# For para operar sobre n primeiros elementos de uma coluna numérica escolhida
soma = 0
lista = list(df[coluna_numerica][:5])
for n in lista:
    soma += n
print("Soma dos 5 primeiros valores:", soma)

print(lista)

# While: Encontrar o primeiro valor maior que um certo limite, definido de acordo com os dados
limite = 83.658544  # Ajuste conforme o contexto da coluna escolhida
i = 0
while i < len(lista) and lista[i] <= limite:
    i += 1
if i < len(lista):
    print("Primeiro valor >", limite, "encontrado:", lista[i])
else:
    print("Nenhum valor maior que", limite, "encontrado nos primeiros 5.")

print(len(lista))
print(i)

"""Insight: Usando a lista na coluna PRICEEACH, verifiquei nos 5 primeiros valores, 3 estão acima da média dos valores.
O primeiro valor é 95.7

5. Operadores Aritméticos e Manipulação de Dados
Realize operações matemáticas (soma, subtração, multiplicação ou divisão) entre colunas ou valores de interesse da base (ex: diferença de duas notas, preço com desconto, etc).
Crie uma nova coluna no DataFrame aplicando um cálculo simples.
"""

#Verificando o dataset
df.tail()

#Verificando os tipos de dados
print(df.dtypes)

if 'SALES' in df.columns and 'PRICEEACH' in df.columns:
    df['Diferenca'] = df['SALES'] - df['PRICEEACH']
    print(df[['SALES', 'PRICEEACH', 'Diferenca']].head())

# Exemplo: preço com desconto
if 'SALES' in df.columns:
    df['Desconto'] = df['SALES'] * 0.1
    print(df[['SALES', 'Desconto']].head())

"""Insight: vericando a diferença da vendas pela o preço da unidade, nas 5 primeiras linha apresentou grande diferença, devido a quantidades de unidades vendidas. criado a uma coluna de desconto, aplicando 10% em cada valor das vendas na coluna 'SALES'

6. NumPy e Arrays Numéricos
Crie um array NumPy a partir de uma coluna numérica da base.
Realize pelo menos duas operações vetorizadas com esse array (ex: somar, multiplicar, elevar ao quadrado elementos).
Mostre como acessar, modificar e exibir partes do array (fatiamento/slicing ou indexação).
Mostre como fazer uma operação agregada, como soma ou média, sobre o array.
"""

array = np.array(df['PRICEEACH'])

# Operações NumPy
array_somado = array + 10
array_quadrado = array ** 2
array_filtrado = array[array < 83]
array_valor_menos = array - 20
print(array[:5])
print("Somado + 10 em cada valor do array",array_somado[:5])
print("Elevado cada valor ao quadrado no array",array_quadrado[:5])
print("Filtrando os valores menores que 83",array_filtrado[:5])
print("Valor menos 20 em cada valor do array",array_valor_menos[:5])

print("Soma dos elementos:", array.sum())
print("Média dos elementos:", array.mean())

"""Insight: utilizando o array, posso aplica uma aumento no valor unitario em cada produto, utilizando exemplo de soma e media no array.
Filtrando os valores menores que a media, aplicando uma redução de -20 em cada valor unitario.

7. Acesso e Manipulação de Dados com Pandas
Selecione linhas/colunas específicas usando .loc, .iloc ou filtrando por condição.
Use algum método de pandas para contar ou agrupar informações simples (ex: .value_counts(), .groupby()), mostrando o resultado em Markdown.
Crie uma pequena análise agregada interessante (ex: número de filmes por país, quantidade de alunos por escola, vendas por categoria).
"""

print(df.head())

#Usando o loc como exemplo das primeiras 5 linhas
df.loc[0:5, ['QUANTITYORDERED','PRICEEACH','PRODUCTLINE','SALES']]

#Usando o iloc como exemplo das primeiras 5 linhas e as 4 primeiras colunas
df.iloc[0:5, 0:3]

print(df.groupby('PRODUCTLINE')['SALES'].sum())
print(df.groupby('PRODUCTLINE')['QUANTITYORDERED'].sum())
#

"""Insight: separando os dados linha de produção, com a quantidade de pedidos, valores unitario e valores das vendas, verificando o produto Classic Cars teve maior quantidade de pedidos.

8. Visualização de Dados
Obrigatório gerar pelo menos 1 gráfico de cada tipo básico:
Gráfico de Linha: ilustrando tendências/séries temporais quando possível.
Gráfico de Barras: comparando categorias relevantes.
Gráfico de Dispersão: mostrando a relação entre duas variáveis numéricas.
Se algum dos gráficos não for aplicável à sua base, crie (ou simule) dados para mostrar que compreendeu o recurso.
Para cada gráfico, escreva em Markdown um comentário sobre o que ele mostra.
"""

df.dtypes

# Gráfico de Linha (ex: evolução temporal; use 'Data' se houver)

if 'ORDERDATE' in df.columns and 'SALES' in df.columns:
    df.groupby('ORDERDATE')['SALES'].sum().plot(kind='line')
    plt.title('Evolução no tempo')
    plt.xlabel('Date')
    plt.ylabel('SALES')
    plt.show()

"""Gráfico de quantidade de vendas pela data"""

# Gráfico de Barras (categorias)
if 'COUNTRY' in df.columns and 'QUANTITYORDERED' in df.columns:
    df.groupby('COUNTRY')['QUANTITYORDERED'].sum().plot(kind='bar')
    plt.title('Total por categoria')
    plt.xlabel('COUNTRY')
    plt.ylabel('QUANTITYORDERED')
    plt.show()

"""Insight: Gráfico de quantidade de pedidos por pais, mostrando que o Pais USA tem a maior quandidade de pedidos."""

# Gráfico de Dispersão (duas numéricas)
if 'QUANTITYORDERED' in df.columns and 'SALES' in df.columns:
    plt.scatter(df['QUANTITYORDERED'], df['SALES'])
    plt.title('Dispersão')
    plt.xlabel('QUANTITYORDERED')
    plt.ylabel('SALES')
    plt.show()

"""Insight: Gráfico de dispersão a quantidade de pedidos pela vendas, verificado que a dispesão esta em torno de 20 a 50 pedidos com valores de vendas de 1000 a 8000

9. Relatório e Insights
Após os usos de listas, dicionários, tuplas, operações, agrupamentos e gráficos, escreva em Markdown sempre que descobrir algo interessante, curioso ou surpreendente.

Inclua um relatório final em Markdown:

Neste projeto, explorei a base sales_data_sample.csv, que mostra a vendas de varios tipos de veiculos como: avião, navios, carros, motos, etc..,
com os status: Shipped, Disputed, In Process, Cancelled, On Hold, Resolved.
Usando a lista na coluna PRICEEACH, verifiquei nos 5 primeiros valores, 3 estão acima da média dos valores que é 83. O primeiro valor é 95.7
Verificando a diferença da vendas pela o preço da unidade, nas 5 primeiras linha apresentou grande diferença, devido a quantidades de unidades vendidas. criado a uma coluna de desconto, aplicando 10% em cada valor das vendas na coluna 'SALES'.
Utilizando o array, posso aplica uma aumento no valor unitario em cada produto, utilizando exemplo de soma e media no array. Filtrando os valores menores que a media, aplicando uma redução de -20 em cada valor unitario.
Separando os dados linha de produção, com a quantidade de pedidos, valores unitário e valores das vendas, verificando o produto Classic Cars teve maior quantidade de pedidos, gráfico de quantidade de pedidos por pais, mostrando que o Pais USA tem a maior quandidade de pedidos e o gráfico de dispersão a quantidade de pedidos pela vendas, verificado que a dispesão esta em torno de 20 a 50 pedidos com valores de vendas de 1000 a 8000.
"""